[package]
name = "guest_number"
version = "0.1.0"
authors = ["wangming1993 <wangming19932008@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
